<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    InstaSIM_KbankQR
 * @copyright  Copyright (c) 2022 Instasim Co. Ltd.
 * @copyright  Copyright (c) 2008 Andrej Sinicyn
 * @copyright  Copyright (c) 2010-2018 Phoenix Media GmbH & Co. KG (http://www.phoenix-media.eu)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<p>
    <?php echo $this->getMethod()->getTitle(); ?><br />
    <?php $_helper = Mage::helper('kbankqr'); ?>
    <?php if ($_instructions = $this->getInstructions()): ?>
        <?php echo nl2br($_instructions); ?><br />
        <?php if ($_order = $this->getInfo()->getOrder()): ?>
            <?php echo $_helper->getQrCodeImageTag($_order->getIncrementId()); ?>
        <?php endif; ?>
    <?php endif; ?>
</p>
